sonar.projectKey=CRRU-UK_photo-id-app
sonar.organization=crru

sonar.sources=src/
sonar.tests=src/
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.cpd.exclusions=**/*.test.ts,**/*.test.tsx
sonar.typescript.tsconfigPaths=tsconfig.json
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.coverage.exclusions=src/**/*.gen.ts,src/index.tsx,src/main.ts,src/preload.ts,src/types.ts,src/contexts/**,src/routes/**,src/backend/menu.ts,src/frontend/components/**,src/frontend/hooks/**

sonar.issue.ignore.multicriteria=e1

# Electron window
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S7764
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*
