sonar.typescript.tsconfigPaths=tsconfig.json

sonar.cpd.exclusions=**/*.test.ts,**/*.test.tsx
sonar.javascript.lcov.reportPaths=./coverage/lcov.info

sonar.issue.ignore.multicriteria=e1

# Electron window
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S7764
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*
