name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-app:
    runs-on: ubuntu-latest

    name: Test app

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6.4.0
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Audit dependencies
        run: npm audit --omit=dev

      - name: Test linting
        run: npm run test:linting

      - name: Test types
        run: npm run test:types

      - name: Run unit tests
        run: npm run test:unit

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  test-e2e:
    needs: test-app

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    name: E2E (${{ matrix.os }})

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6.0.2

      - uses: ./.github/actions/e2e

  test-terraform:
    runs-on: ubuntu-latest

    name: Test Terraform

    permissions:
      contents: read

    defaults:
      run:
        working-directory: terraform

    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4.0.0
        with:
          terraform_version: "~> 1.14.5"

      - name: Test formatting
        run: terraform fmt -list=true -check -recursive -diff
